# Generated by Django 5.0 on 2024-01-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='problem',
            field=models.TextField(),
        ),
    ]
